Fix conversion: add float() call
t0mer/py-weatheril pull request #27
Opened 2023-05-27 18:54 UTC by benyaming

Sometimes the UV data comes as a float string ('0.8'), and it causes `ValueError: invalid literal for int() with base 10: '0.8'`

2023-05-28 07:14 UTC, GuyKh requested changes
Thanks for the PR.
But why cast a float into an int?
See my comment

2023-05-28 07:14 UTC, GuyKh commented on weatheril/__init__.py
> +                               u_v_i_factor=int(float(analysis_data.get("u_v_i_factor", "0")) or "0"),
```suggestion
                               u_v_i_factor=float(analysis_data.get("u_v_i_factor", "0") or "0"),
```

2023-05-28 17:24 UTC, GuyKh commented on weatheril/__init__.py
> +                               u_v_i_factor=int(float(analysis_data.get("u_v_i_factor", "0")) or "0"),
Also, need to modify `u_v_i_factor` type
https://github.com/t0mer/py-weatheril/blob/main/weatheril/weather.py#L24

2023-05-29 12:36 UTC, benyaming commented
I just tried to keep the type signature. Do you think it is better to switch to float and do not round the value?

2023-05-29 13:11 UTC, benyaming commented
@GuyKh changed to float 👍 

Also, I'm not sure about `u_v_index` and `u_v_i_max`, since I haven't found any documentation of the API

2023-05-29 16:31 UTC, GuyKh approved these changes
LGTM 👍🏻

2023-05-29 16:31 UTC, merged